/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    accordion: AccordionTypes;
    gallery: GalleryTypes;
    parallaxText: ParallaxTextTypes;
    journey: JourneyTypes;
    imageFullScreen: ImageFullScreenTypes;
    quotes: QuotesTypes;
    textImageBlock: TextImageBlockTypes;
    tabs: TabsTypes;
    teaser: TeaserTypes;
    videoFullScreen: VideoFullScreenTypes;
  };
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('de' | 'en' | 'fr' | 'it' | 'es' | 'br' | 'pl' | 'ko' | 'mx' | 'cz' | 'hu' | 'sk' | 'cn')
    | ('de' | 'en' | 'fr' | 'it' | 'es' | 'br' | 'pl' | 'ko' | 'mx' | 'cz' | 'hu' | 'sk' | 'cn')[];
  globals: {
    home: Home;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'de' | 'en' | 'fr' | 'it' | 'es' | 'br' | 'pl' | 'ko' | 'mx' | 'cz' | 'hu' | 'sk' | 'cn';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionTypes".
 */
export interface AccordionTypes {
  title: string;
  /**
   * Optional field
   */
  description?: string | null;
  accordionItems?:
    | {
        headline: string;
        expandedText: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional field
         */
        disable?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryTypes".
 */
export interface GalleryTypes {
  /**
   * Optional field
   */
  headline?: string | null;
  items: {
    title: string;
    description: string;
    image: string | Media;
    id?: string | null;
  }[];
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ParallaxTextTypes".
 */
export interface ParallaxTextTypes {
  text: string;
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'parallaxText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JourneyTypes".
 */
export interface JourneyTypes {
  items: {
    headline: string;
    description: string;
    image: string | Media;
    copy: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'journey';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageFullScreenTypes".
 */
export interface ImageFullScreenTypes {
  copy: {
    headline: string;
    description: string;
    /**
     * Optional field
     */
    underline?: string | null;
  };
  image: string | Media;
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageFullScreen';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuotesTypes".
 */
export interface QuotesTypes {
  text: string;
  authorInfo: {
    name: string;
    /**
     * Marketing Department, Management Department, etc. (Optional field)
     */
    position?: string | null;
  };
  image: string | Media;
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quotes';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageBlockTypes".
 */
export interface TextImageBlockTypes {
  title?: string | null;
  portableText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  imageContent?: {
    /**
     * Optional field, when image is selected – it will be placed under the rich text in UI
     */
    image?: (string | null) | Media;
    /**
     * Optional field
     */
    underline?: string | null;
  };
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textImageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsTypes".
 */
export interface TabsTypes {
  /**
   * Optional field
   */
  headline?: string | null;
  /**
   * Optional field
   */
  description?: string | null;
  tabsList: {
    label: string;
    value: string;
    tabsContent?: (QuotesTypes | TextImageBlockTypes | GalleryTypes)[] | null;
    id?: string | null;
  }[];
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeaserTypes".
 */
export interface TeaserTypes {
  headline?: string | null;
  teaserItems: {
    overline: string;
    text: string;
    description?: string | null;
    image?: (string | null) | Media;
    video?: (string | null) | Media;
    internalPageLink?: (string | null) | Page;
    /**
     * Enter a full URL to an external page (e.g. https://example.com)
     */
    externalPageLink?: string | null;
    id?: string | null;
  }[];
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'teaser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  meta?: {
    /**
     * Used in <title> and SEO.
     */
    title?: string | null;
    /**
     * Used in <meta name='description'> for SEO.
     */
    description?: string | null;
    /**
     * Used for Open Graph and Twitter Card.
     */
    image?: (string | null) | Media;
  };
  title: string;
  slug: string;
  /**
   * When true - using for pages with text content only
   */
  textContentOnly?: boolean | null;
  goBackButtonText?: string | null;
  content: TextImageBlockTypes[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoFullScreenTypes".
 */
export interface VideoFullScreenTypes {
  copy: {
    headline: string;
    description?: string | null;
  };
  /**
   * Embed iframe, provide the ID of the video
   */
  video: string;
  previewImage: string | Media;
  /**
   * Write down to which anchor tag this block should be linked (see Navigation Links slug)
   */
  anchorNavigation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoFullScreen';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  title?: T;
  slug?: T;
  textContentOnly?: T;
  goBackButtonText?: T;
  content?:
    | T
    | {
        textImageBlock?: T | TextImageBlockTypesSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageBlockTypes_select".
 */
export interface TextImageBlockTypesSelect<T extends boolean = true> {
  title?: T;
  portableText?: T;
  imageContent?:
    | T
    | {
        image?: T;
        underline?: T;
      };
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Main Page Content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  meta?: {
    /**
     * Used in <title> and SEO.
     */
    title?: string | null;
    /**
     * Used in <meta name='description'> for SEO.
     */
    description?: string | null;
    /**
     * Used for Open Graph and Twitter Card.
     */
    image?: (string | null) | Media;
  };
  pageName: string;
  /**
   * Page name which shows in URL
   */
  slug: string;
  contentBlocks: (
    | AccordionTypes
    | GalleryTypes
    | ParallaxTextTypes
    | JourneyTypes
    | ImageFullScreenTypes
    | QuotesTypes
    | TextImageBlockTypes
    | TabsTypes
    | TeaserTypes
    | VideoFullScreenTypes
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  navigationLinks: {
    title: string;
    /**
     * Anchor tag to navigate through page
     */
    slug?: string | null;
    id?: string | null;
  }[];
  copy?: {
    promotionText?: string | null;
    underline?: string | null;
  };
  /**
   * Only mp4, mpeg, or mov videos allowed
   */
  video: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  parallaxText: string;
  logoUrl?: {
    internalPageLink?: (string | null) | Page;
    /**
     * Enter a full URL to an external page (e.g. https://example.com)
     */
    externalPageLink?: string | null;
  };
  /**
   * Policies, cookie, etc.
   */
  infoFields: {
    infoText?: string | null;
    internalPageLink?: (string | null) | Page;
    /**
     * Enter a full URL to an external page (e.g. https://example.com)
     */
    externalPageLink?: string | null;
    id?: string | null;
  }[];
  socialIconsFields: {
    icon?:
      | ('facebook' | 'instagram' | 'twitter' | 'linkedin' | 'wechat' | 'weibo' | 'whatsapp' | 'xing' | 'youtube')
      | null;
    internalPageLink?: (string | null) | Page;
    /**
     * Enter a full URL to an external page (e.g. https://example.com)
     */
    externalPageLink?: string | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  pageName?: T;
  slug?: T;
  contentBlocks?:
    | T
    | {
        accordion?: T | AccordionTypesSelect<T>;
        gallery?: T | GalleryTypesSelect<T>;
        parallaxText?: T | ParallaxTextTypesSelect<T>;
        journey?: T | JourneyTypesSelect<T>;
        imageFullScreen?: T | ImageFullScreenTypesSelect<T>;
        quotes?: T | QuotesTypesSelect<T>;
        textImageBlock?: T | TextImageBlockTypesSelect<T>;
        tabs?: T | TabsTypesSelect<T>;
        teaser?: T | TeaserTypesSelect<T>;
        videoFullScreen?: T | VideoFullScreenTypesSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionTypes_select".
 */
export interface AccordionTypesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  accordionItems?:
    | T
    | {
        headline?: T;
        expandedText?: T;
        disable?: T;
        id?: T;
      };
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryTypes_select".
 */
export interface GalleryTypesSelect<T extends boolean = true> {
  headline?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ParallaxTextTypes_select".
 */
export interface ParallaxTextTypesSelect<T extends boolean = true> {
  text?: T;
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JourneyTypes_select".
 */
export interface JourneyTypesSelect<T extends boolean = true> {
  items?:
    | T
    | {
        headline?: T;
        description?: T;
        image?: T;
        copy?: T;
        id?: T;
      };
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageFullScreenTypes_select".
 */
export interface ImageFullScreenTypesSelect<T extends boolean = true> {
  copy?:
    | T
    | {
        headline?: T;
        description?: T;
        underline?: T;
      };
  image?: T;
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuotesTypes_select".
 */
export interface QuotesTypesSelect<T extends boolean = true> {
  text?: T;
  authorInfo?:
    | T
    | {
        name?: T;
        position?: T;
      };
  image?: T;
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsTypes_select".
 */
export interface TabsTypesSelect<T extends boolean = true> {
  headline?: T;
  description?: T;
  tabsList?:
    | T
    | {
        label?: T;
        value?: T;
        tabsContent?:
          | T
          | {
              quotes?: T | QuotesTypesSelect<T>;
              textImageBlock?: T | TextImageBlockTypesSelect<T>;
              gallery?: T | GalleryTypesSelect<T>;
            };
        id?: T;
      };
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeaserTypes_select".
 */
export interface TeaserTypesSelect<T extends boolean = true> {
  headline?: T;
  teaserItems?:
    | T
    | {
        overline?: T;
        text?: T;
        description?: T;
        image?: T;
        video?: T;
        internalPageLink?: T;
        externalPageLink?: T;
        id?: T;
      };
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoFullScreenTypes_select".
 */
export interface VideoFullScreenTypesSelect<T extends boolean = true> {
  copy?:
    | T
    | {
        headline?: T;
        description?: T;
      };
  video?: T;
  previewImage?: T;
  anchorNavigation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  navigationLinks?:
    | T
    | {
        title?: T;
        slug?: T;
        id?: T;
      };
  copy?:
    | T
    | {
        promotionText?: T;
        underline?: T;
      };
  video?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  parallaxText?: T;
  logoUrl?:
    | T
    | {
        internalPageLink?: T;
        externalPageLink?: T;
      };
  infoFields?:
    | T
    | {
        infoText?: T;
        internalPageLink?: T;
        externalPageLink?: T;
        id?: T;
      };
  socialIconsFields?:
    | T
    | {
        icon?: T;
        internalPageLink?: T;
        externalPageLink?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}